osx_image: xcode9
language: objective-c
install:
  - ./install_swiftlint.sh
script:
    - |
      xcodebuild clean build test \
      -project FRDIntent.xcodeproj \
      -scheme FRDIntent \
      -sdk iphonesimulator \
      -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' \
      ONLY_ACTIVE_ARCH=NO

    - swiftlint